spring.application.name=data-trans
server.port=8080

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=C##HCNC
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update

# HikariCP Connection Pool ??
spring.datasource.hikari.maximum-pool-size=10  # ?? ?? ?
spring.datasource.hikari.minimum-idle=5        # ?? ?? ?? ?
spring.datasource.hikari.idle-timeout=30000   # ?? ??? ???? (ms)
spring.datasource.hikari.connection-timeout=30000  # ??? ???? (ms)
spring.datasource.hikari.max-lifetime=1800000    # ??? ?? ?? (ms)


spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true